version: '3'
services:

  survey_api:
    build: .
    ports:
      - 9001:8000
    volumes:
      - .:/home/node/brickdev
    depends_on:
      - survey_mongo
    
  survey_mongo:
    image: mongo:3.0-wheezy
    ports:
      - 27017
    volumes:
       - ./database:/data/db